// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmuprojuqziklmpcygjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdXByb2p1cXppa2xtcGN5Z2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODM2MTAsImV4cCI6MjA3MDA1OTYxMH0.eYpnGl6Q6k0-Q6hQmazW_KltGOxn29dhce6bL7lHw_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});